export type ScreenType =
  | 'home'
  | 'explorer'
  | 'evaluator'
  | 'builder'
  | 'simulation'
  | 'data-room'
  | 'target-ranking'
  | 'reports'
  | 'exploration-dashboard'
  | 'sales-proposals'
  | 'sales-leads'
  | 'feature'
  | 'repo'
  | 'pursuit'
  | 'agents'
  | 'projects'
  | 'project-detail';
